# Name of your site (displayed in the header)
name: Haocheng Lu

# Short bio or description about you (displayed in the header)
description: Junior Computer Science Student at NYU Shanghai, Spring 2025


# URL of your avatar or profile pic
avatar: /LuHC409-weekly/images/icon.png
avatar_alt_text: Avatar

# Use this separator in your blogs to indicate where the abbreviated part ends and the "Read more ..." link appears
excerpt_separator: <!--more-->

# Includes an icon in the footer for each username you enter
footer-links:
  github: ossd-s25
  linkedin: Haocheng Lu

# Your website URL
url: "https://ossd-s25.github.io"
baseurl: "/LuHC409-weekly"

# Permalink structure for posts
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Markdown and syntax highlighting settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded

# Use the following plug-ins
gems:
  - jekyll-sitemap
  - jekyll-feed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
